services:
  - type: web
    name: flask-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
